In [1]:
import torch

In [2]:
a = torch.Tensor(5,4)
b = torch.Tensor(4,6)


### Matrix multiplication

In [4]:
(a@b).shape

torch.Size([5, 6])

In [5]:
(torch.matmul(a,b)).shape

torch.Size([5, 6])

### Elementwise / Hadamard product

In [10]:
c = torch.ones((3,4))*2
d = torch.ones((3,4))*3

In [11]:
c

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [12]:
d

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [13]:
c*d

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])