In [2]:
import torch

### Basic functionality

In [3]:
a = torch.Tensor(3,20)

In [4]:
b = a.view(3,4,-1)


In [5]:
b.shape

torch.Size([3, 4, 5])

### order

In [9]:
a = torch.Tensor(torch.range(1, 16))

/home/alessandro/miniconda3/envs/as_chem/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


In [10]:
a

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16.])

In [11]:
a.view(4,4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

In [12]:
a.view(4,4).view(2,8)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13., 14., 15., 16.]])

### See Pytorch internals writeup http://blog.ezyang.com/2019/05/pytorch-internals/